// ---Auto Generated by dsapr ---
package com.dsapr.vo;

import com.baomidou.mybatisplus.extension.service.IService;
import com.dsapr.test.Student;
import java.lang.Long;

public interface IStudentService extends IService<Student> {
  /**
   * create
   */
  Long createStudent(StudentCreator creator);

  /**
   * update
   */
  void updateStudent(StudentUpdater updater);

  /**
   * valid
   */
  void validStudent(Long id);

  /**
   * invalid
   */
  void invalidStudent(Long id);
}
