// ---Auto Generated by dsapr ---
package com.dsapr.vo;

import com.dsapr.common.model.Request;
import io.swagger.v3.oas.annotations.media.Schema;

@Schema
public class StudentQueryRequest implements Request {
}
