// ---Auto Generated by dsapr ---
package com.dsapr.vo;

import com.dsapr.common.model.Request;
import io.swagger.v3.oas.annotations.media.Schema;
import java.lang.Long;
import java.lang.String;

@Schema
public class StudentUpdateRequest implements Request {
  @Schema(
      title = "name"
  )
  private String name;

  private Long id;

  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Long getId() {
    return id;
  }

  public void setId(long id) {
    this.id = id;
  }
}
