// ---Auto Generated by dsapr ---
package com.dsapr.vo;

import com.dsapr.common.mapper.DateMapper;
import com.dsapr.common.mapper.GenericEnumMapper;
import com.dsapr.test.Student;
import org.mapstruct.Mapper;
import org.mapstruct.factory.Mappers;

@Mapper(
    uses = {
        GenericEnumMapper.class,
        DateMapper.class
    }
)
public interface StudentMapper {
  StudentMapper INSTANCE = Mappers.getMapper(StudentMapper.class);

  Student dtoToEntity(StudentCreator dto);

  StudentQuery request2Query(StudentQueryRequest request);
}
