// ---Auto Generated by dsapr ---
package com.dsapr.vo;

import com.dsapr.mybatis.support.BaseRepository;
import com.dsapr.test.Student;

public interface StudentRepository extends BaseRepository<Student> {
}
